import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');
const domain = read('src','PublisherStudio.Web','BusinessObjects','AutomationModels.cs');
const services = read('src','PublisherStudio.Web','Services','Automation','IAutomationServices.cs');
const queues = read('src','PublisherStudio.Web','Services','Automation','BrowserAutomationServices.cs');
const controller = read('src','PublisherStudio.Web','Controllers','AutomationController.cs');
const runtime = read('src','PublisherStudio.Web','wwwroot','js','automationInterop.js');
const app = read('src','PublisherStudio.Web','Components','App.razor');
for (const contract of ['BrowserAutomationCommand','BrowserScreenshotRequest','BusinessObjectContextSnapshot','ServiceApiDescriptor']) assert.match(domain, new RegExp(contract));
for (const contract of ['IUserInputAutomationService','IScreenshotCaptureService','IBusinessObjectContextService','IApiSurfaceCatalogService']) assert.match(services, new RegExp(contract));
assert.match(queues, /ConcurrentDictionary/);
for (const route of ['api/automation/input','api/automation/screenshots','api/domain-context']) assert.ok(controller.includes(route));
assert.match(controller, /Download\(Guid id\)/);
for (const behavior of ['MouseEvent','PointerEvent','KeyboardEvent','html2canvas','/api/automation/input/pending','/api/automation/screenshots/pending']) assert.ok(runtime.includes(behavior));
assert.match(app, /automationInterop\.js/);
console.log('LocalGPT/AICouncil browser input, screenshot queue, completion, download and domain-context API contracts passed');
