import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const security = read('src/PublisherStudio.Web/Services/OrganicPlugins/OrganicRuntimeSecurityService.cs');
const globals = read('src/PublisherStudio.Web/GlobalUsings.OneWire.cs');
const installer = read('src/PublisherStudio.InstallerConsole/Program.cs');
const host = read('src/PublisherStudio.Web/Services/ApplicationHostServices.cs');
const build = read('Build-LocalDevelopment.ps1');
const project = read('src/PublisherStudio.Web/PublisherStudio.Web.csproj');
const settings = JSON.parse(read('src/PublisherStudio.Web/appsettings.json'));
const launch = JSON.parse(read('src/PublisherStudio.Web/Properties/launchSettings.json'));
const installerProject = read('src/PublisherStudio.InstallerConsole/PublisherStudio.InstallerConsole.csproj');
const installLauncher = read('src/PublisherStudio.InstallerConsole/Install.cmd');
const updateLauncher = read('src/PublisherStudio.InstallerConsole/Update.cmd');
const startLauncher = read('src/PublisherStudio.InstallerConsole/Start.cmd');
const uninstallLauncher = read('src/PublisherStudio.InstallerConsole/Uninstall.cmd');
assert.match(security, /using LocalGPT\.WireProtocol;/);
assert.match(security, /ProtocolVersion\s*=\s*OneWireProtocol\.Version/);
assert.match(globals, /global using LocalGPT\.WireProtocol;/);
assert.match(installer, /WaitForRuntimeEndpoint/);
assert.match(installer, /TryGetRunningEndpoint/);
assert.match(installer, /PublisherStudio is already running: \{existingUrl\}/);
assert.match(installer, /PublisherStudio is ready: \{url\}/);
assert.match(installer, /PublisherStudio startup failed/);
assert.match(installer, /PublisherStudio startup failed[\s\S]*throw;/);
assert.doesNotMatch(installer, /Doomland|Your args to string|args were initially empty/);
assert.match(installerProject, /<None Update="\*\.cmd" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" \/>/);
assert.match(installLauncher, /--install-blazorpublisher --install-ffmpeg --start-blazorpublisher --port 58071 --shortcuts/);
assert.doesNotMatch(installLauncher, /--force-delete/);
assert.match(updateLauncher, /--update-blazorpublisher --install-ffmpeg --start-blazorpublisher --port 58071 --shortcuts/);
assert.doesNotMatch(updateLauncher, /--force-delete/);
assert.match(startLauncher, /--start-blazorpublisher --port 58071/);
assert.match(uninstallLauncher, /--uninstall --force-delete/);
assert.doesNotMatch(installer, /Thread\.Sleep\(TimeSpan\.FromSeconds\(2\)\)/);
assert.match(host, /systemVariables\.DefaultPort/);
assert.equal(settings.PublisherStudio.SystemVariables['Application.DefaultPort'], '58071');
assert.match(build, /Assert-OneWireArchitecture\.ps1/);
assert.match(project, /PackageReference Include="LocalGPT\.WireProtocolVersion"/);
assert.doesNotMatch(project, /ProjectReference[^\n]+LocalGPT\.WireProtocolVersion/);
assert.equal(settings.PublisherStudio.Port, 58071);
assert.equal(settings.OrganicPlugins.ServicePort, 51140);
assert.equal(settings.OrganicPlugins.DiscoveryPort, 51141);
assert.equal(settings.OrganicPlugins.BroadcastAddress, '255.255.255.255');
assert.equal(launch.profiles['PublisherStudio.Web'].applicationUrl, 'http://127.0.0.1:58071');
console.log('PASS PublisherStudio compiler namespace, process-owned startup URL, package authority and 1-Wire default safeguards.');
