import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');
const domain = read('src','PublisherStudio.Web','Domain','OpenScadModels.cs');
const catalog = read('src','PublisherStudio.Web','Services','OpenScad','OpenScadCatalogService.cs');
const contracts = read('src','PublisherStudio.Web','Services','OpenScad','IOpenScadServices.cs');
const document = read('src','PublisherStudio.Web','Services','OpenScad','OpenScadDocumentService.cs');
const renderers = read('src','PublisherStudio.Web','Services','OpenScad','OpenScadNodeRenderers.cs');
const controller = read('src','PublisherStudio.Web','Controllers','OpenScadController.cs');
for (const model of ['OpenScadCodePart','OpenScadNode','OpenScadDocument','OpenScadAnimationTrack','OpenScadNodeDefinition','OpenScadParameterDefinition']) assert.match(domain, new RegExp(`class ${model}`));
for (const kind of ['cube','sphere','cylinder','polyhedron','square','circle','polygon','text','translate','rotate','scale','resize','mirror','multmatrix','color','offset','union','difference','intersection','hull','minkowski','render','linear_extrude','rotate_extrude','projection','import','surface','module_call','raw']) assert.ok(catalog.includes(`"${kind}"`), `${kind} missing from OpenSCAD catalog`);
assert.match(contracts, /interface IOpenScadNodeRenderer/);
assert.match(renderers, /CanRender\(OpenScadNode node\)/);
assert.doesNotMatch(renderers, /private\s+static/);
assert.match(document, /ps_track\(\$t/);
assert.match(document, /TargetNodeId/);
assert.match(document, /CodeParts/);
assert.match(document, /ValidateParameter/);
assert.match(document, /IOpenScadNodeRenderer/);
for (const route of ['nodes/{kind}/default','catalog','validate','generate','video-layer','format-value','identifier','quote']) assert.ok(controller.includes(route));
console.log('open OpenSCAD node graph, basic figure catalog, renderer registry, part animation, validation and controller contracts passed');
