import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');

const models = read('src/PublisherStudio.Web/BusinessObjects/PublicationModels.cs');
const panelModels = read('src/PublisherStudio.Web/BusinessObjects/PublicationPanelModels.cs');
const traversal = read('src/PublisherStudio.Web/Services/PublicationElementTraversal.cs');
const panels = read('src/PublisherStudio.Web/Services/Panels/PanelDocumentService.cs');
const panelView = read('src/PublisherStudio.Web/Components/Editor/PanelView.razor');
const panelStudio = read('src/PublisherStudio.Web/Components/Editor/PanelStudio.razor');
const panelLibrary = read('src/PublisherStudio.Web/Components/Editor/PanelLibrary.razor');
const editor = read('src/PublisherStudio.Web/Components/Pages/Editor.razor');
const ribbon = read('src/PublisherStudio.Web/Components/Editor/PublicationRibbon.razor');
const inspector = read('src/PublisherStudio.Web/Components/Editor/InspectorPanel.razor');
const pageSurface = read('src/PublisherStudio.Web/Components/Editor/PageSurface.razor');
const print = read('src/PublisherStudio.Web/Components/Editor/PrintPublication.razor');
const runtime = read('src/PublisherStudio.Web/wwwroot/js/componentRuntime.js');
const converter = read('src/PublisherStudio.Web/Services/MediaConversion/MediaConversionService.cs');
const converterInterface = read('src/PublisherStudio.Web/Services/MediaConversion/IMediaConversionService.cs');
const converterController = read('src/PublisherStudio.Web/Controllers/MediaConversionController.cs');
const converterStudio = read('src/PublisherStudio.Web/Components/Editor/MediaConverterStudio.razor');
const program = read('src/PublisherStudio.Web/Program.cs');
const applicationComposition = read('src/PublisherStudio.Web/PublisherStudioServiceCollectionExtensions.cs');
const appsettings = JSON.parse(read('src/PublisherStudio.Web/appsettings.json'));
const packageJson = JSON.parse(read('src/PublisherStudio.Web/package.json'));
const lockJson = JSON.parse(read('src/PublisherStudio.Web/package-lock.json'));
const webProject = read('src/PublisherStudio.Web/PublisherStudio.Web.csproj');
const installerProject = read('src/PublisherStudio.InstallerConsole/PublisherStudio.InstallerConsole.csproj');

assert.match(models, /PublicationElementKind[^\n]*Panel, HtmlEmbed/);
assert.match(models, /JsonDerivedType\(typeof\(PanelElement\), "panel"\)/);
assert.match(models, /JsonDerivedType\(typeof\(HtmlEmbedElement\), "htmlEmbed"\)/);
assert.match(models, /FormatVersion \{ get; set; \} = "1\.55"/);
assert.match(panelModels, /sealed class PanelElement : PublicationElement/);
assert.match(panelModels, /List<PublicationPanelView> Views/);
assert.match(panelModels, /sealed class HtmlEmbedElement : PublicationElement/);
assert.match(traversal, /if \(element is not PanelElement panel\) continue/);
assert.match(panels, /kpi-dashboard/);
assert.match(panels, /creator-hub/);
assert.match(panels, /PanelDocumentService\([\s\S]*?PublicationDataService data,[\s\S]*?PublicationComponentService components,[\s\S]*?ILogger<PanelDocumentService>\? logger = null\)/);
assert.match(panels, /_components\.Create\(document, PublicationComponentKind\.Chat\)/);
assert.match(panels, /PublicationChatPlatform\.OutputContext/);
assert.match(panels, /_components\.Normalize\(document, component\)/);
assert.doesNotMatch(panels, /PublicationLiveSourceKind\.PlatformChat/, 'Platform chat is a shared interactive component, not a browser capture source.');
assert.match(panels, /web-experience/);
assert.match(panelView, /case DataVisualElement/);
assert.match(panelView, /case DevExtremeComponentElement/);
assert.match(panelView, /case LiveSourceElement/);
assert.match(panelView, /case PanelElement nestedPanel/);
assert.match(panelView, /case HtmlEmbedElement/);
assert.match(panelStudio, /Panel \/ Div Studio/);
assert.match(panelStudio, /Import standalone HTML/);
assert.match(panelStudio, /Panels\.CreateComponentTool\(Document, toolId\)/);
assert.match(panels, /_components\.Create\(document, kind\)/);
assert.match(panels, /PublicationLiveSourceKind\.Camera/);
assert.match(panelLibrary, /GetPresets/);
assert.match(editor, /<PanelStudio/);
assert.match(editor, /<MediaConverterStudio/);
assert.match(editor, /PanelLibraryVisible/);
assert.match(ribbon, /Panel \/ dashboard/);
assert.match(ribbon, /Media Converter Studio/);
assert.match(inspector, /OnInsertPanel/);
assert.match(inspector, /OnOpenMediaConverter/);
assert.match(pageSurface, /case PanelElement panel/);
assert.match(print, /case PanelElement panel/);
assert.match(runtime, /data-panel-root/);
assert.match(runtime, /startPanels/);
assert.match(runtime, /refreshPanels/);

assert.match(converterInterface, /Task<MediaConversionJobInfo> QueueAsync/);
assert.match(converter, /_ffmpegLocator\.Resolve/);
assert.match(converter, /UseShellExecute = false/);
assert.match(converter, /startInfo\.ArgumentList\.Add/);
assert.match(converter, /webm-vp9/);
assert.match(converter, /image-webp-lossless/);
assert.match(converter, /image-avif/);
assert.doesNotMatch(converter, /ProcessStartInfo[^}]*Arguments\s*=/s, 'FFmpeg arguments must not be shell-concatenated.');
assert.match(converterController, /\[Route\("api\/media-conversion"\)\]/);
assert.match(converterController, /\[HttpPost\("jobs"\)\]/);
assert.match(converterController, /jobs\/\{id:guid\}\/file/);
assert.match(converterStudio, /Insert Mainframe/);
assert.match(applicationComposition, /AddSingleton<IMediaConversionService, MediaConversionService>/);
assert.match(applicationComposition, /AddSingleton<PanelDocumentService, PanelDocumentService>/);
assert.equal(appsettings.PublisherStudio.FFmpegPath, '');

assert.equal(packageJson.version, '2.1.8');
assert.equal(lockJson.version, '2.1.8');
assert.equal(lockJson.packages[''].version, '2.1.8');
assert.match(webProject, /<Version>2\.1\.7<\/Version>/);
assert.match(installerProject, /<Version>2\.1\.7<\/Version>/);

console.log('Panel/Div Studio, recursive shared-component rendering, dashboard library, FFmpeg service/controller/UI, and version contracts passed.');
