import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');
const changelog = read('CHANGELOG-v2.1.1.md');
const validation = read('VALIDATION.md');
const developer = read('docs','articles','developer-build.md');
const release = read('RELEASE.md');
assert.match(changelog, /Installer and deployment/);
assert.match(changelog, /LocalGPT-style ZIP extraction/);
assert.match(validation, /2\.1\.1/);
assert.match(developer, /one concise changelog and one validation report/);
assert.match(developer, /Old work diaries and personal progress notes are not part of the public documentation/);
assert.match(release, /2\.1\.1/);
assert.equal(fs.existsSync(path.join(root, 'docs', 'architecture', 'task-ledger.md')), false);
console.log('release changelog, validation, and consolidated documentation contracts passed');
