import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');
const runtime = read('src','PublisherStudio.Web','wwwroot','js','publisherInterop.js');
const ribbon = read('src','PublisherStudio.Web','Components','Editor','PublicationRibbon.razor');
const catalog = read('src','PublisherStudio.Web','Services','Configuration','RenderExportCatalogService.cs');
const api = read('src','PublisherStudio.Web','Controllers','ConfigurationController.cs');
for (const functionName of ['createFrozenRasterImage','snapshotCanvasForRaster','snapshotIframeForRaster','freezeMediaForRaster']) assert.match(runtime, new RegExp(`function ${functionName}`));
assert.match(runtime, /canvas\.toDataURL/);
assert.match(runtime, /drawImage\(video/);
assert.match(runtime, /cloneCanvas\.replaceWith/);
for (const label of ['Render current page as PNG (video + effects)','Render current page as JPEG (video + effects)','Render current page as SVG (frozen media)']) assert.ok(ribbon.includes(label));
for (const format of ['png','jpg','svg','html','pdf']) assert.ok(catalog.includes(`Format = "${format}"`));
assert.match(catalog, /RenderBeforeExport/);
assert.match(api, /api\/render-export/);
console.log('non-breaking canvas/video/iframe freeze pipeline, explicit render export commands and capability API contracts passed');
