import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const runtime = read('src/PublisherStudio.Web/wwwroot/js/automationInterop.js');
const controller = read('src/PublisherStudio.Web/Controllers/AutomationController.cs');
const organicPage = read('src/PublisherStudio.Web/Components/Pages/OrganicPlugins.razor');
const discovery = read('src/PublisherStudio.Web/HostedServices/OrganicPlugins/LocalGptDiscoveryHostedService.cs');
const options = read('src/PublisherStudio.Web/Domain/OrganicPluginModels.cs');
const program = read('src/PublisherStudio.Web/Program.cs');
const localization = read('src/PublisherStudio.Web/Services/Configuration/FileLocalizationService.cs');
const settings = JSON.parse(read('src/PublisherStudio.Web/appsettings.json'));
assert.ok(!runtime.includes("DOMContentLoaded', () => window.publisherAutomation.start()"));
assert.match(runtime, /enableForSession/);
assert.match(runtime, /sessionStorage\.getItem\(storageKey\) === 'true'/);
assert.match(runtime, /api\/automation\/runtime\/status/);
assert.match(runtime, /setTimeout\(poll, 2000\)/);
assert.match(controller, /AutomationRuntimeController/);
assert.match(controller, /connection\.State\.IsLinked \? Ok\(input\.ClaimPending/);
assert.match(controller, /Browser automation requires an explicitly linked LocalGPT peer/);
assert.match(controller, /Browser screenshot automation requires an explicitly linked LocalGPT peer/);
assert.match(organicPage, /Enable browser automation for this tab/);
assert.match(organicPage, /publisherAutomation\.enableForSession/);
assert.match(organicPage, /publisherAutomation\.disableForSession/);
assert.match(options, /AutoConnectDiscoveredPeer \{ get; set; \} = false/);
assert.equal(settings.OrganicPlugins.AutoConnectDiscoveredPeer, false);
assert.match(discovery, /Automatically opening the local 1-Wire transport/);
assert.match(discovery, /human link\/MFA approval remains required/);
assert.match(discovery, /IPAddress\.IsLoopback/);
assert.match(discovery, /Environment\.MachineName/);
assert.match(discovery, /automaticallyAttemptedPeers/);
assert.doesNotMatch(program, /new AcceptLanguageHeaderRequestCultureProvider\(\)/);
assert.match(program, /new CookieRequestCultureProvider\(\)/);
assert.match(localization, /requiredKeys\.All\(translated\.ContainsKey\)/);
console.log('PASS explicit linked automation, optional local transport discovery, and single-language culture safeguards.');
