import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');
const composition = read('src','PublisherStudio.Web','PublisherStudioServiceCollectionExtensions.cs');
const program = read('src','PublisherStudio.Web','Program.cs');
const context = read('src','PublisherStudio.Web','Services','Automation','BusinessObjectContextService.cs');
const apiAdapter = read('src','PublisherStudio.Web','Controllers','ApiSurfaceCatalogService.cs');
const interchange = read('src','PublisherStudio.Web','Services','VideoStudio','Export','VideoLayerInterchangeService.cs');
const interchangeApi = read('src','PublisherStudio.Web','Controllers','VideoLayerInterchangeController.cs');
assert.match(program, /AddPublisherStudioApplication/);
for (const contract of ['IApplicationPortResolver','IRuntimeEndpointWriter','IPolygonGeometryService','IBrowserRuntimeTemplateService','IOpenScadDocumentService','IOpenScadNodeFactoryService','IUserInputAutomationService','IScreenshotCaptureService','ICodeFormattingService','IFileLocalizationService']) assert.match(composition, new RegExp(contract));
assert.match(composition, /AddScoped<EditorStateService/);
assert.match(composition, /ServiceArchitectureDescriptor/);
assert.match(composition, /AddArchitectureDescriptors/);
assert.doesNotMatch(context, /Microsoft\.AspNetCore\.Mvc/);
assert.match(context, /IApiSurfaceCatalogService/);
assert.match(apiAdapter, /ControllerBase/);
assert.match(apiAdapter, /ServiceContracts/);
assert.match(interchange, /public interface IVideoLayerInterchangeService/);
assert.doesNotMatch(interchange, /private\s+static/);
for (const route of ['default-blob','geometry/resample','geometry/openscad-points','runtime/blob']) assert.ok(interchangeApi.includes(route));
console.log('interface-first DI lifetime, MVC adapter boundary, business-object context, and reusable video interchange API contracts passed');
