import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');
const project = read('src','PublisherStudio.Web','PublisherStudio.Web.csproj');
const program = read('src','PublisherStudio.Web','Program.cs');
const languages = read('src','PublisherStudio.Web','Services','CodeEditing','CodeLanguageService.cs');
const formatting = read('src','PublisherStudio.Web','Services','CodeEditing','CodeFormattingService.cs');
const controller = read('src','PublisherStudio.Web','Controllers','CodeController.cs');
const story = read('src','PublisherStudio.Web','Components','Editor','StoryEditor.razor');
const config = read('src','PublisherStudio.Web','appsettings.json');
for (const culture of ['en-US','de-DE','es-ES','ja-JP']) {
  const data = JSON.parse(read('src','PublisherStudio.Web','Localization',`${culture}.json`));
  assert.ok(Object.keys(data).length > 0, `${culture} localization is empty`);
}
for (const pkg of ['DevExpress.Blazor.de','DevExpress.Blazor.es','DevExpress.Blazor.ja','DevExpress.Blazor.RichEdit.de','DevExpress.Blazor.RichEdit.es','DevExpress.Blazor.RichEdit.ja']) assert.ok(project.includes(pkg));
assert.match(program, /UseRequestLocalization/);
assert.match(program, /RichEdit\.SpellCheck/);
assert.match(program, /AddSpellCheck\(\)/);
for (const language of ['csharp','javascript','typescript','html','css','json','yaml','markdown','sql','python','powershell','bash','cpp','java','rust','go','php','ruby','swift','openscad']) assert.ok(languages.includes(`"${language}"`));
assert.match(formatting, /ToggleComment/);
assert.match(formatting, /runtimePatterns\.GetRegex\(PublisherRuntimePattern\.CodeString\)/);
assert.match(formatting, /runtimePatterns\.GetRegex\(PublisherRuntimePattern\.CodeNumber\)/);
for (const route of ['languages','detect','format','comment','analyze']) assert.ok(controller.includes(route));
assert.match(story, /DxRibbonTab Text="Code"/);
assert.match(story, /CheckSpelling="true"/);
assert.match(story, /Insert code at caret/);
assert.match(config, /"Images"/);
assert.match(config, /"OpenScad"/);
console.log('file localization, DevExpress satellite resources, spellcheck, configurable paths and multi-language code editing contracts passed');
