import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');
const story = read('src/PublisherStudio.Web/Components/Editor/StoryEditor.razor');
const resultInterface = read('src/PublisherStudio.Web/Services/OrganicPlugins/IOrganicPluginServices.cs');
const resultStore = read('src/PublisherStudio.Web/Services/OrganicPlugins/OrganicPluginStateServices.cs');
const capabilities = read('src/PublisherStudio.Web/Services/OrganicPlugins/OrganicCapabilityAndExecutionServices.cs');
const project = read('src/PublisherStudio.Web/PublisherStudio.Web.csproj');
assert.match(story, /CanUseAiCouncil => LocalGptConnection\.State\.IsLinked/);
assert.match(story, /publisher\.text\.insert\.propose/);
assert.match(story, /InsertAiProposalAsync/);
assert.match(story, /ActiveSubDocument\.AddTextAsync\(_selection\.CaretPosition, proposal\.Text\)/);
assert.match(story, /The user reviews and explicitly inserts the proposal/);
assert.match(resultInterface, /event Action\? Changed/);
assert.match(resultInterface, /bool RemoveTextProposal\(Guid id\)/);
assert.match(resultStore, /Changed\?\.Invoke\(\)/);
assert.match(capabilities, /RequiresCurrentBrowserSessionPermission = true/);
assert.match(capabilities, /BrowserPermissionCannotBePreGrantedByLocalGpt = true/);
assert.match(project, /PackageReference Include="LocalGPT\.WireProtocolVersion"/);
assert.doesNotMatch(project, /ProjectReference[^>]*LocalGPT\.WireProtocolVersion/);
console.log('paired StoryEditor Council proposal, explicit insertion, browser-session permission and package authority contracts passed');
