### YamlMime:ManagedReference
items:
- uid: PublisherStudio.Services.Automation
  commentId: N:PublisherStudio.Services.Automation
  id: Automation
  parent: PublisherStudio.Services
  children:
  - PublisherStudio.Services.Automation.BusinessObjectContextService
  - PublisherStudio.Services.Automation.IApiSurfaceCatalogService
  - PublisherStudio.Services.Automation.IBusinessObjectContextService
  - PublisherStudio.Services.Automation.IScreenshotCaptureService
  - PublisherStudio.Services.Automation.IServiceArchitectureRegistry
  - PublisherStudio.Services.Automation.IUserInputAutomationService
  - PublisherStudio.Services.Automation.ScreenshotCaptureService
  - PublisherStudio.Services.Automation.ServiceArchitectureDescriptor
  - PublisherStudio.Services.Automation.ServiceArchitectureRegistry
  - PublisherStudio.Services.Automation.UserInputAutomationService
  langs:
  - csharp
  - vb
  name: PublisherStudio.Services.Automation
  nameWithType: PublisherStudio.Services.Automation
  fullName: PublisherStudio.Services.Automation
  type: Namespace
  assemblies:
  - PublisherStudio.Web
references:
- uid: PublisherStudio.Services.Automation.BusinessObjectContextService
  commentId: T:PublisherStudio.Services.Automation.BusinessObjectContextService
  isExternal: true
  href: PublisherStudio.Services.Automation.BusinessObjectContextService.html
  name: BusinessObjectContextService
  nameWithType: BusinessObjectContextService
  fullName: PublisherStudio.Services.Automation.BusinessObjectContextService
- uid: PublisherStudio.Services.Automation.IApiSurfaceCatalogService
  commentId: T:PublisherStudio.Services.Automation.IApiSurfaceCatalogService
  parent: PublisherStudio.Services.Automation
  isExternal: true
  href: PublisherStudio.Services.Automation.IApiSurfaceCatalogService.html
  name: IApiSurfaceCatalogService
  nameWithType: IApiSurfaceCatalogService
  fullName: PublisherStudio.Services.Automation.IApiSurfaceCatalogService
- uid: PublisherStudio.Services.Automation.IBusinessObjectContextService
  commentId: T:PublisherStudio.Services.Automation.IBusinessObjectContextService
  parent: PublisherStudio.Services.Automation
  isExternal: true
  href: PublisherStudio.Services.Automation.IBusinessObjectContextService.html
  name: IBusinessObjectContextService
  nameWithType: IBusinessObjectContextService
  fullName: PublisherStudio.Services.Automation.IBusinessObjectContextService
- uid: PublisherStudio.Services.Automation.IScreenshotCaptureService
  commentId: T:PublisherStudio.Services.Automation.IScreenshotCaptureService
  parent: PublisherStudio.Services.Automation
  isExternal: true
  href: PublisherStudio.Services.Automation.IScreenshotCaptureService.html
  name: IScreenshotCaptureService
  nameWithType: IScreenshotCaptureService
  fullName: PublisherStudio.Services.Automation.IScreenshotCaptureService
- uid: PublisherStudio.Services.Automation.IServiceArchitectureRegistry
  commentId: T:PublisherStudio.Services.Automation.IServiceArchitectureRegistry
  parent: PublisherStudio.Services.Automation
  isExternal: true
  href: PublisherStudio.Services.Automation.IServiceArchitectureRegistry.html
  name: IServiceArchitectureRegistry
  nameWithType: IServiceArchitectureRegistry
  fullName: PublisherStudio.Services.Automation.IServiceArchitectureRegistry
- uid: PublisherStudio.Services.Automation.IUserInputAutomationService
  commentId: T:PublisherStudio.Services.Automation.IUserInputAutomationService
  parent: PublisherStudio.Services.Automation
  isExternal: true
  href: PublisherStudio.Services.Automation.IUserInputAutomationService.html
  name: IUserInputAutomationService
  nameWithType: IUserInputAutomationService
  fullName: PublisherStudio.Services.Automation.IUserInputAutomationService
- uid: PublisherStudio.Services.Automation.ScreenshotCaptureService
  commentId: T:PublisherStudio.Services.Automation.ScreenshotCaptureService
  isExternal: true
  href: PublisherStudio.Services.Automation.ScreenshotCaptureService.html
  name: ScreenshotCaptureService
  nameWithType: ScreenshotCaptureService
  fullName: PublisherStudio.Services.Automation.ScreenshotCaptureService
- uid: PublisherStudio.Services.Automation.ServiceArchitectureDescriptor
  commentId: T:PublisherStudio.Services.Automation.ServiceArchitectureDescriptor
  parent: PublisherStudio.Services.Automation
  isExternal: true
  href: PublisherStudio.Services.Automation.ServiceArchitectureDescriptor.html
  name: ServiceArchitectureDescriptor
  nameWithType: ServiceArchitectureDescriptor
  fullName: PublisherStudio.Services.Automation.ServiceArchitectureDescriptor
- uid: PublisherStudio.Services.Automation.ServiceArchitectureRegistry
  commentId: T:PublisherStudio.Services.Automation.ServiceArchitectureRegistry
  isExternal: true
  href: PublisherStudio.Services.Automation.ServiceArchitectureRegistry.html
  name: ServiceArchitectureRegistry
  nameWithType: ServiceArchitectureRegistry
  fullName: PublisherStudio.Services.Automation.ServiceArchitectureRegistry
- uid: PublisherStudio.Services.Automation.UserInputAutomationService
  commentId: T:PublisherStudio.Services.Automation.UserInputAutomationService
  isExternal: true
  href: PublisherStudio.Services.Automation.UserInputAutomationService.html
  name: UserInputAutomationService
  nameWithType: UserInputAutomationService
  fullName: PublisherStudio.Services.Automation.UserInputAutomationService
- uid: PublisherStudio.Services.Automation
  commentId: N:PublisherStudio.Services.Automation
  isExternal: true
  href: PublisherStudio.html
  name: PublisherStudio.Services.Automation
  nameWithType: PublisherStudio.Services.Automation
  fullName: PublisherStudio.Services.Automation
  spec.csharp:
  - uid: PublisherStudio
    name: PublisherStudio
    isExternal: true
    href: PublisherStudio.html
  - name: .
  - uid: PublisherStudio.Services
    name: Services
    isExternal: true
    href: PublisherStudio.Services.html
  - name: .
  - uid: PublisherStudio.Services.Automation
    name: Automation
    isExternal: true
    href: PublisherStudio.Services.Automation.html
  spec.vb:
  - uid: PublisherStudio
    name: PublisherStudio
    isExternal: true
    href: PublisherStudio.html
  - name: .
  - uid: PublisherStudio.Services
    name: Services
    isExternal: true
    href: PublisherStudio.Services.html
  - name: .
  - uid: PublisherStudio.Services.Automation
    name: Automation
    isExternal: true
    href: PublisherStudio.Services.Automation.html
