### YamlMime:ManagedReference
items:
- uid: PublisherStudio.Services.Streaming.Settings
  commentId: N:PublisherStudio.Services.Streaming.Settings
  id: Settings
  parent: PublisherStudio.Services.Streaming
  children:
  - PublisherStudio.Services.Streaming.Settings.PublicationStreamingSettingsStore
  langs:
  - csharp
  - vb
  name: PublisherStudio.Services.Streaming.Settings
  nameWithType: PublisherStudio.Services.Streaming.Settings
  fullName: PublisherStudio.Services.Streaming.Settings
  type: Namespace
  assemblies:
  - PublisherStudio.Web
references:
- uid: PublisherStudio.Services.Streaming.Settings.PublicationStreamingSettingsStore
  commentId: T:PublisherStudio.Services.Streaming.Settings.PublicationStreamingSettingsStore
  parent: PublisherStudio.Services.Streaming.Settings
  isExternal: true
  href: PublisherStudio.Services.Streaming.Settings.PublicationStreamingSettingsStore.html
  name: PublicationStreamingSettingsStore
  nameWithType: PublicationStreamingSettingsStore
  fullName: PublisherStudio.Services.Streaming.Settings.PublicationStreamingSettingsStore
- uid: PublisherStudio.Services.Streaming.Settings
  commentId: N:PublisherStudio.Services.Streaming.Settings
  isExternal: true
  href: PublisherStudio.html
  name: PublisherStudio.Services.Streaming.Settings
  nameWithType: PublisherStudio.Services.Streaming.Settings
  fullName: PublisherStudio.Services.Streaming.Settings
  spec.csharp:
  - uid: PublisherStudio
    name: PublisherStudio
    isExternal: true
    href: PublisherStudio.html
  - name: .
  - uid: PublisherStudio.Services
    name: Services
    isExternal: true
    href: PublisherStudio.Services.html
  - name: .
  - uid: PublisherStudio.Services.Streaming
    name: Streaming
    isExternal: true
    href: PublisherStudio.Services.Streaming.html
  - name: .
  - uid: PublisherStudio.Services.Streaming.Settings
    name: Settings
    isExternal: true
    href: PublisherStudio.Services.Streaming.Settings.html
  spec.vb:
  - uid: PublisherStudio
    name: PublisherStudio
    isExternal: true
    href: PublisherStudio.html
  - name: .
  - uid: PublisherStudio.Services
    name: Services
    isExternal: true
    href: PublisherStudio.Services.html
  - name: .
  - uid: PublisherStudio.Services.Streaming
    name: Streaming
    isExternal: true
    href: PublisherStudio.Services.Streaming.html
  - name: .
  - uid: PublisherStudio.Services.Streaming.Settings
    name: Settings
    isExternal: true
    href: PublisherStudio.Services.Streaming.Settings.html
