### YamlMime:ManagedReference
items:
- uid: PublisherStudio.Services.Configuration
  commentId: N:PublisherStudio.Services.Configuration
  id: Configuration
  parent: PublisherStudio.Services
  children:
  - PublisherStudio.Services.Configuration.ApplicationPathService
  - PublisherStudio.Services.Configuration.FileLocalizationService
  - PublisherStudio.Services.Configuration.IApplicationPathService
  - PublisherStudio.Services.Configuration.IFileLocalizationService
  - PublisherStudio.Services.Configuration.IPanelStudioTextPatternDataService
  - PublisherStudio.Services.Configuration.IPublisherDxFunctionCatalogDataService
  - PublisherStudio.Services.Configuration.IPublisherRuntimePatternService
  - PublisherStudio.Services.Configuration.IPublisherRuntimePolicyDataService
  - PublisherStudio.Services.Configuration.IRenderExportCatalogService
  - PublisherStudio.Services.Configuration.ISystemVariableStoreService
  - PublisherStudio.Services.Configuration.OrganicConnectionRuntimeStateService
  - PublisherStudio.Services.Configuration.OrganicReplayPolicyDataService
  - PublisherStudio.Services.Configuration.PanelStudioTextPatternDataService
  - PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDataService
  - PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDocument
  - PublisherStudio.Services.Configuration.PublisherRuntimePatternService
  - PublisherStudio.Services.Configuration.PublisherRuntimePolicyDataService
  - PublisherStudio.Services.Configuration.RenderExportCatalogService
  - PublisherStudio.Services.Configuration.SystemVariableStoreService
  langs:
  - csharp
  - vb
  name: PublisherStudio.Services.Configuration
  nameWithType: PublisherStudio.Services.Configuration
  fullName: PublisherStudio.Services.Configuration
  type: Namespace
  assemblies:
  - PublisherStudio.Web
references:
- uid: PublisherStudio.Services.Configuration.ApplicationPathService
  commentId: T:PublisherStudio.Services.Configuration.ApplicationPathService
  isExternal: true
  href: PublisherStudio.Services.Configuration.ApplicationPathService.html
  name: ApplicationPathService
  nameWithType: ApplicationPathService
  fullName: PublisherStudio.Services.Configuration.ApplicationPathService
- uid: PublisherStudio.Services.Configuration.FileLocalizationService
  commentId: T:PublisherStudio.Services.Configuration.FileLocalizationService
  isExternal: true
  href: PublisherStudio.Services.Configuration.FileLocalizationService.html
  name: FileLocalizationService
  nameWithType: FileLocalizationService
  fullName: PublisherStudio.Services.Configuration.FileLocalizationService
- uid: PublisherStudio.Services.Configuration.IApplicationPathService
  commentId: T:PublisherStudio.Services.Configuration.IApplicationPathService
  parent: PublisherStudio.Services.Configuration
  isExternal: true
  href: PublisherStudio.Services.Configuration.IApplicationPathService.html
  name: IApplicationPathService
  nameWithType: IApplicationPathService
  fullName: PublisherStudio.Services.Configuration.IApplicationPathService
- uid: PublisherStudio.Services.Configuration.IFileLocalizationService
  commentId: T:PublisherStudio.Services.Configuration.IFileLocalizationService
  parent: PublisherStudio.Services.Configuration
  isExternal: true
  href: PublisherStudio.Services.Configuration.IFileLocalizationService.html
  name: IFileLocalizationService
  nameWithType: IFileLocalizationService
  fullName: PublisherStudio.Services.Configuration.IFileLocalizationService
- uid: PublisherStudio.Services.Configuration.IPanelStudioTextPatternDataService
  commentId: T:PublisherStudio.Services.Configuration.IPanelStudioTextPatternDataService
  parent: PublisherStudio.Services.Configuration
  isExternal: true
  href: PublisherStudio.Services.Configuration.IPanelStudioTextPatternDataService.html
  name: IPanelStudioTextPatternDataService
  nameWithType: IPanelStudioTextPatternDataService
  fullName: PublisherStudio.Services.Configuration.IPanelStudioTextPatternDataService
- uid: PublisherStudio.Services.Configuration.IPublisherDxFunctionCatalogDataService
  commentId: T:PublisherStudio.Services.Configuration.IPublisherDxFunctionCatalogDataService
  parent: PublisherStudio.Services.Configuration
  isExternal: true
  href: PublisherStudio.Services.Configuration.IPublisherDxFunctionCatalogDataService.html
  name: IPublisherDxFunctionCatalogDataService
  nameWithType: IPublisherDxFunctionCatalogDataService
  fullName: PublisherStudio.Services.Configuration.IPublisherDxFunctionCatalogDataService
- uid: PublisherStudio.Services.Configuration.IPublisherRuntimePatternService
  commentId: T:PublisherStudio.Services.Configuration.IPublisherRuntimePatternService
  parent: PublisherStudio.Services.Configuration
  isExternal: true
  href: PublisherStudio.Services.Configuration.IPublisherRuntimePatternService.html
  name: IPublisherRuntimePatternService
  nameWithType: IPublisherRuntimePatternService
  fullName: PublisherStudio.Services.Configuration.IPublisherRuntimePatternService
- uid: PublisherStudio.Services.Configuration.IPublisherRuntimePolicyDataService
  commentId: T:PublisherStudio.Services.Configuration.IPublisherRuntimePolicyDataService
  parent: PublisherStudio.Services.Configuration
  isExternal: true
  href: PublisherStudio.Services.Configuration.IPublisherRuntimePolicyDataService.html
  name: IPublisherRuntimePolicyDataService
  nameWithType: IPublisherRuntimePolicyDataService
  fullName: PublisherStudio.Services.Configuration.IPublisherRuntimePolicyDataService
- uid: PublisherStudio.Services.Configuration.IRenderExportCatalogService
  commentId: T:PublisherStudio.Services.Configuration.IRenderExportCatalogService
  parent: PublisherStudio.Services.Configuration
  isExternal: true
  href: PublisherStudio.Services.Configuration.IRenderExportCatalogService.html
  name: IRenderExportCatalogService
  nameWithType: IRenderExportCatalogService
  fullName: PublisherStudio.Services.Configuration.IRenderExportCatalogService
- uid: PublisherStudio.Services.Configuration.ISystemVariableStoreService
  commentId: T:PublisherStudio.Services.Configuration.ISystemVariableStoreService
  parent: PublisherStudio.Services.Configuration
  isExternal: true
  href: PublisherStudio.Services.Configuration.ISystemVariableStoreService.html
  name: ISystemVariableStoreService
  nameWithType: ISystemVariableStoreService
  fullName: PublisherStudio.Services.Configuration.ISystemVariableStoreService
- uid: PublisherStudio.Services.Configuration.OrganicConnectionRuntimeStateService
  commentId: T:PublisherStudio.Services.Configuration.OrganicConnectionRuntimeStateService
  isExternal: true
  href: PublisherStudio.Services.Configuration.OrganicConnectionRuntimeStateService.html
  name: OrganicConnectionRuntimeStateService
  nameWithType: OrganicConnectionRuntimeStateService
  fullName: PublisherStudio.Services.Configuration.OrganicConnectionRuntimeStateService
- uid: PublisherStudio.Services.Configuration.OrganicReplayPolicyDataService
  commentId: T:PublisherStudio.Services.Configuration.OrganicReplayPolicyDataService
  isExternal: true
  href: PublisherStudio.Services.Configuration.OrganicReplayPolicyDataService.html
  name: OrganicReplayPolicyDataService
  nameWithType: OrganicReplayPolicyDataService
  fullName: PublisherStudio.Services.Configuration.OrganicReplayPolicyDataService
- uid: PublisherStudio.Services.Configuration.PanelStudioTextPatternDataService
  commentId: T:PublisherStudio.Services.Configuration.PanelStudioTextPatternDataService
  isExternal: true
  href: PublisherStudio.Services.Configuration.PanelStudioTextPatternDataService.html
  name: PanelStudioTextPatternDataService
  nameWithType: PanelStudioTextPatternDataService
  fullName: PublisherStudio.Services.Configuration.PanelStudioTextPatternDataService
- uid: PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDataService
  commentId: T:PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDataService
  isExternal: true
  href: PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDataService.html
  name: PublisherDxFunctionCatalogDataService
  nameWithType: PublisherDxFunctionCatalogDataService
  fullName: PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDataService
- uid: PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDocument
  commentId: T:PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDocument
  isExternal: true
  href: PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDocument.html
  name: PublisherDxFunctionCatalogDocument
  nameWithType: PublisherDxFunctionCatalogDocument
  fullName: PublisherStudio.Services.Configuration.PublisherDxFunctionCatalogDocument
- uid: PublisherStudio.Services.Configuration.PublisherRuntimePatternService
  commentId: T:PublisherStudio.Services.Configuration.PublisherRuntimePatternService
  isExternal: true
  href: PublisherStudio.Services.Configuration.PublisherRuntimePatternService.html
  name: PublisherRuntimePatternService
  nameWithType: PublisherRuntimePatternService
  fullName: PublisherStudio.Services.Configuration.PublisherRuntimePatternService
- uid: PublisherStudio.Services.Configuration.PublisherRuntimePolicyDataService
  commentId: T:PublisherStudio.Services.Configuration.PublisherRuntimePolicyDataService
  isExternal: true
  href: PublisherStudio.Services.Configuration.PublisherRuntimePolicyDataService.html
  name: PublisherRuntimePolicyDataService
  nameWithType: PublisherRuntimePolicyDataService
  fullName: PublisherStudio.Services.Configuration.PublisherRuntimePolicyDataService
- uid: PublisherStudio.Services.Configuration.RenderExportCatalogService
  commentId: T:PublisherStudio.Services.Configuration.RenderExportCatalogService
  isExternal: true
  href: PublisherStudio.Services.Configuration.RenderExportCatalogService.html
  name: RenderExportCatalogService
  nameWithType: RenderExportCatalogService
  fullName: PublisherStudio.Services.Configuration.RenderExportCatalogService
- uid: PublisherStudio.Services.Configuration.SystemVariableStoreService
  commentId: T:PublisherStudio.Services.Configuration.SystemVariableStoreService
  isExternal: true
  href: PublisherStudio.Services.Configuration.SystemVariableStoreService.html
  name: SystemVariableStoreService
  nameWithType: SystemVariableStoreService
  fullName: PublisherStudio.Services.Configuration.SystemVariableStoreService
- uid: PublisherStudio.Services.Configuration
  commentId: N:PublisherStudio.Services.Configuration
  isExternal: true
  href: PublisherStudio.html
  name: PublisherStudio.Services.Configuration
  nameWithType: PublisherStudio.Services.Configuration
  fullName: PublisherStudio.Services.Configuration
  spec.csharp:
  - uid: PublisherStudio
    name: PublisherStudio
    isExternal: true
    href: PublisherStudio.html
  - name: .
  - uid: PublisherStudio.Services
    name: Services
    isExternal: true
    href: PublisherStudio.Services.html
  - name: .
  - uid: PublisherStudio.Services.Configuration
    name: Configuration
    isExternal: true
    href: PublisherStudio.Services.Configuration.html
  spec.vb:
  - uid: PublisherStudio
    name: PublisherStudio
    isExternal: true
    href: PublisherStudio.html
  - name: .
  - uid: PublisherStudio.Services
    name: Services
    isExternal: true
    href: PublisherStudio.Services.html
  - name: .
  - uid: PublisherStudio.Services.Configuration
    name: Configuration
    isExternal: true
    href: PublisherStudio.Services.Configuration.html
